name: example
description: sezinsoft_lint_rules example.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  sezinsoft_lint_rules:
    path: ../
flutter:
  uses-material-design: true
